Bookers/config/routes.rb
Rails.application.routes.draw do
  resources :books

  root to:'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord

    validates :title,presence: true
    validates :body,presence: true
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books=Book.all
    @book=Book.new
  end

  def create
     @book=Book.new(book_params)
    if @book.save
      flash[:notice] ="Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      render :index
    end
  end

  def show
    @books=Book.find(params[:id])
  end

  def destroy
    book=Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  def edit
    @book=Book.find(params[:id])

  end


  def update
    book=Book.find(params[:id])

    if book.update(book_params)
      flash[:notice] ="Book was successfully created."
      redirect_to book_path(book.id)
    else
      @book=book
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

Bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%=form_with model: @book,ulr:book_path(@book.id),method: :patch do |f|%>

    <% if @book.errors.any?%>
     <div class="error">
       <span class=error_text><%=@book.errors.count %>errors prohibited this book from being saved:</span>
       <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
    　　<% end %>
       </ul>
     </div>

    <%end%>

    <h4>Title</h4>
    <%=f.text_field :title%>

    <h4>body</h4>
    <%=f.text_area :body%>

    <span class="button"><%=f.submit'Update Book'%></span>

    <%=link_to "show",book_path(@book.id)%>

    |

    <%=link_to "Back",books_path%>
<%end%>

Bookers/app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3">
    </tr>
  </thead>

  <tbody>
    <%=@books.each do |book|%>
     <tr>
      <td><%=book.title%></td>
      <td><%=book.body%></td>
      <td><%=link_to "Show",book_path(book.id)%></td>
      <td><%=link_to "Edit",edit_book_path(book.id)%></td>
      <td><%=link_to "Destroy",book_path(book.id),method: :delete,"data-confirm"=>"Are you sure?"%></td>
     </tr>
    <%end%>
  </tbody>

</table>

<h2>New book</h2>



<%=form_with model:@book,url:'/books',method: :post do |b|%>

 <% if @book.errors.any?%>
  <div class="error">
    <span class=error_text><%=@book.errors.count %>errors prohibited this book from being saved:</span>
       <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
    　　<% end %>
       </ul>
  </div>

 <% end %>


  <div class="title_field">
   <h4>Title</h4>
   <%=b.text_field:title %>
  </div>
  <div class="body_area">
   <h4>Body</h4>
   <%=b.text_area:body %>
  </div>
   <span class="button"><%=b.submit 'Create Book' %></span>

<% end %>

Bookers/app/views/books/show.html.erb
<p><strong>Title</strong>:<%=@books.title%></p>


<p><strong>Body</strong>:<%=@books.body%></p>

<%=link_to "Edit",edit_book_path(@books.id)%>

|

<%=link_to "Back",books_path%>

Bookers/app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することができます
</p>
<p><%=link_to "start",books_path%></p>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if flash[:notice] %>
    <div class="flash">
         <%= flash[:notice] %>
    </div>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>